### ISSUE TITLE
VTK dependency should be pinned to 8.1.1 for macOS?

### ISSUE THREAD

**Issue by christianbrodbeck** [conda-forge/mayavi-feedstock#28]
It looks like (at least on macOS) the default `vtk` installed is 8.1, however this leads to an error when trying to import `mlab`. After forcing `vtk` to 8.1.1 the error disappears (see below). I assume this is not an issue for other platforms, since it has not been brought up before?

Fails:
```
$ conda create -n test1 -c conda-forge mayavi 
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/test1

  added / updated specs: 
    - mayavi


The following NEW packages will be INSTALLED:

    apptools:        4.4.0-py36_2           conda-forge
    bzip2:           1.0.6-1                conda-forge
    ca-certificates: 2018.8.24-ha4d7672_0   conda-forge
    certifi:         2018.8.24-py36_1       conda-forge
    configobj:       5.0.6-py_0             conda-forge
    envisage:        4.7.0-py_0             conda-forge
    expat:           2.2.5-hfc679d8_2       conda-forge
    freetype:        2.8.1-hfa320df_1       conda-forge
    future:          0.16.0-py36_2          conda-forge
    hdf5:            1.10.1-2               conda-forge
    icu:             58.2-hfc679d8_0        conda-forge
    jpeg:            9c-h470a237_1          conda-forge
    jsoncpp:         1.8.4-h2d50403_0       conda-forge
    libffi:          3.2.1-hfc679d8_5       conda-forge
    libgfortran:     3.0.1-h93005f0_2                  
    libiconv:        1.15-h470a237_3        conda-forge
    libopenblas:     0.2.20-hdc02c5d_7                 
    libpng:          1.6.34-ha92aebf_2      conda-forge
    libtiff:         4.0.9-he6b73bb_2       conda-forge
    libxml2:         2.9.8-h422b904_4       conda-forge
    mayavi:          4.6.2-py36h18b3941_1   conda-forge
    ncurses:         6.1-hfc679d8_1         conda-forge
    numpy:           1.14.3-py36he6379a5_1             
    numpy-base:      1.14.3-py36h7ef55bc_1             
    openssl:         1.0.2p-h470a237_0      conda-forge
    pip:             18.0-py36_1            conda-forge
    pyface:          6.0.0-py_1             conda-forge
    pygments:        2.2.0-py_1             conda-forge
    pyqt:            5.6.0-py36h8210e8a_7   conda-forge
    python:          3.6.6-h5001a0f_0       conda-forge
    qt:              5.6.2-hd4c90f3_9       conda-forge
    readline:        7.0-haf1bffa_1         conda-forge
    setuptools:      40.2.0-py36_0          conda-forge
    sip:             4.18.1-py36hfc679d8_0  conda-forge
    six:             1.11.0-py36_1          conda-forge
    sqlite:          3.24.0-h2f33b56_1      conda-forge
    tbb:             2018_20171205-0        conda-forge
    tk:              8.6.8-0                conda-forge
    traits:          4.6.0-py36h470a237_2   conda-forge
    traitsui:        6.0.0-py_1             conda-forge
    vtk:             8.1.0-py36h3f2a929_203 conda-forge
    wheel:           0.31.1-py36_1          conda-forge
    xz:              5.2.4-h470a237_1       conda-forge
    zlib:            1.2.11-h470a237_3      conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test1
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate test1
(test1)$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mayavi import mlab 
Traceback (most recent call last):
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: dlopen(/anaconda3/envs/test1/lib/python3.6/site-packages/vtk/vtkIOParallelPython.so, 2): Library not loaded: @rpath/libjsoncpp.11.dylib
  Referenced from: /anaconda3/envs/test1/lib/libvtkIOParallel-8.1.1.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/mayavi/core/engine.py", line 12, in <module>
    import vtk
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/vtk/__init__.py", line 80, in <module>
    from .vtkIOParallel import *
  File "/anaconda3/envs/test1/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'
>>> 
(test1)$ conda deactivate
```

Succeeds:
```
$ conda create -n test2 -c conda-forge mayavi "vtk>8.1.0"
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/test2

  added / updated specs: 
    - mayavi
    - vtk[version='>8.1.0']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libpng-1.6.35              |       ha92aebf_2         321 KB  conda-forge

The following NEW packages will be INSTALLED:

    apptools:        4.4.0-py36_2           conda-forge
    bzip2:           1.0.6-1                conda-forge
    ca-certificates: 2018.8.24-ha4d7672_0   conda-forge
    certifi:         2018.8.24-py36_1       conda-forge
    configobj:       5.0.6-py_0             conda-forge
    curl:            7.61.0-h93b3f91_2      conda-forge
    envisage:        4.7.0-py_0             conda-forge
    expat:           2.2.5-hfc679d8_2       conda-forge
    freetype:        2.8.1-hfa320df_1       conda-forge
    future:          0.16.0-py36_2          conda-forge
    hdf4:            4.2.13-h951d187_2      conda-forge
    hdf5:            1.10.1-2               conda-forge
    icu:             58.2-hfc679d8_0        conda-forge
    jpeg:            9c-h470a237_1          conda-forge
    jsoncpp:         1.8.1-h2d50403_1       conda-forge
    krb5:            1.14.6-0               conda-forge
    libffi:          3.2.1-hfc679d8_5       conda-forge
    libgfortran:     3.0.1-h93005f0_2                  
    libiconv:        1.15-h470a237_3        conda-forge
    libnetcdf:       4.6.1-2                conda-forge
    libogg:          1.3.2-h470a237_1       conda-forge
    libopenblas:     0.2.20-hdc02c5d_7                 
    libpng:          1.6.35-ha92aebf_2      conda-forge
    libssh2:         1.8.0-h5b517e9_2       conda-forge
    libtheora:       1.1.1-h470a237_1       conda-forge
    libtiff:         4.0.9-he6b73bb_2       conda-forge
    libvorbis:       1.3.5-h470a237_1       conda-forge
    libxml2:         2.9.8-h422b904_4       conda-forge
    lz4-c:           1.8.1.2-0              conda-forge
    mayavi:          4.6.2-py36h18b3941_1   conda-forge
    ncurses:         6.1-hfc679d8_1         conda-forge
    numpy:           1.14.3-py36he6379a5_1             
    numpy-base:      1.14.3-py36h7ef55bc_1             
    openssl:         1.0.2p-h470a237_0      conda-forge
    pip:             18.0-py36_1            conda-forge
    pyface:          6.0.0-py_1             conda-forge
    pygments:        2.2.0-py_1             conda-forge
    pyqt:            5.6.0-py36h8210e8a_7   conda-forge
    python:          3.6.6-h5001a0f_0       conda-forge
    qt:              5.6.2-hd4c90f3_9       conda-forge
    readline:        7.0-haf1bffa_1         conda-forge
    setuptools:      40.2.0-py36_0          conda-forge
    sip:             4.18.1-py36hfc679d8_0  conda-forge
    six:             1.11.0-py36_1          conda-forge
    sqlite:          3.24.0-h2f33b56_1      conda-forge
    tbb:             2018_20171205-0        conda-forge
    tk:              8.6.8-0                conda-forge
    traits:          4.6.0-py36h470a237_2   conda-forge
    traitsui:        6.0.0-py_1             conda-forge
    vtk:             8.1.1-py36hdfe3907_203 conda-forge
    wheel:           0.31.1-py36_1          conda-forge
    xz:              5.2.4-h470a237_1       conda-forge
    zlib:            1.2.11-h470a237_3      conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
libpng-1.6.35        | 321 KB    | ################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test2
#
# To deactivate an active environment, use
#
#     $ conda deactivate
$ conda activate test2
(test2)$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mayavi import mlab
>>> 
```

**Comment by larsoner** [comment]
I'll close this since we're up to 9.1 nowadays
