### ISSUE TITLE
missing libjsoncpp.so.11

### ISSUE THREAD

**Issue by smithsp** [conda-forge/mayavi-feedstock#33]
Issue:
Mayavi fails to import into python
```
$ python -c 'import mayavi; import mayavi.mlab'
Traceback (most recent call last):
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: libjsoncpp.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/mayavi/core/engine.py", line 12, in <module>
    import vtk
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/vtk/__init__.py", line 80, in <module>
    from .vtkIOParallel import *
  File "/fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi:
#
# Name                    Version                   Build  Channel
apptools                  4.4.0                 py36_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
envisage                  4.7.1                      py_0    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
future                    0.17.1                py36_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsoncpp                   1.8.4             h6bb024c_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
mayavi                    4.6.2            py36h18b3941_1    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.16.2           py36h8b7e671_1    conda-forge
openblas                  0.3.5                ha44fe06_0    conda-forge
openssl                   1.0.2r               h14c3975_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.0.3                   py36_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyface                    6.0.0                      py_1    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
python                    3.6.5                         1    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.20.1                        2    conda-forge
tbb                       2019.5               hc9558a2_0    conda-forge
tk                        8.6.7                         0    omfit
traits                    5.0.0            py36h14c3975_0    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
vtk                       8.1.0           py36h3f2a929_203    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : mayavi
    active env location : /fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi
            shell level : 1
       user config file : /home/smithsp/.condarc
 populated config files : /home/smithsp/.condarc
          conda version : 4.6.2
    conda-build version : 3.10.9
         python version : 2.7.15.final.0
       base environment : /fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/omfit/linux-64
                          https://conda.anaconda.org/omfit/noarch
                          https://conda.anaconda.org/aaronkho/linux-64
                          https://conda.anaconda.org/aaronkho/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/pkgs
                          /home/smithsp/.conda/pkgs
       envs directories : /fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs
                          /home/smithsp/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.2 requests/2.20.1 CPython/2.7.15 Linux/2.6.32-754.10.1.el6.x86_64 centos/6.10 glibc/2.12
                UID:GID : 2294:2294
             netrc file : None
           offline mode : False
```
</details>

**Comment by grlee77** [comment]
I think this is the same issue reported in #28 (albeit on linux rather than OS X in this case).

I will try to merge #32 later today and hopefully, the new build of the package will resolve the issue.

**Comment by smithsp** [comment]
I agree that this is a duplicate.  The title of #28 didn't look relevant enough for me to look at its details.  Next time I will search a little better.  Thanks.

**Comment by smithsp** [comment]
I can confirm that with `conda install 'vtk>8.1.0'` this works.  Thanks.

**Comment by grlee77** [comment]
I am assuming this was with an existing build of `mayavi` and not the build that was just merged in #32? Do you mind pasting the output of `conda list mayavi` here?

It is possible that we should have pinned specifically to `8.1.2` in #32 instead of `8.1.*`. However, I think `8.1.2` is the olddest VTK version built since conda-forge's recent compiler update, so it may already effectively only allow installation with `8.1.2`. 

I have opened a new PR in #34 to create a separate build pinned to vtk 8.2.

**Comment by smithsp** [comment]
```
$ conda list
# packages in environment at /fusion/projects/codes/atom/omfit_v1/atom_SATURN_GCC/miniconda2/envs/mayavi:
#
# Name                    Version                   Build  Channel
apptools                  4.4.0                 py36_1002    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
dbus                      1.13.2               h714fa37_1  
envisage                  4.7.1                      py_0    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
future                    0.17.1                py36_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsoncpp                   1.8.4             h6bb024c_1001    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libogg                    1.3.2             h14c3975_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libssh2                   1.8.2                h22169c7_1    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtheora                 1.1.1             h14c3975_1001    conda-forge
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.5             h14c3975_1001    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
lz4-c                     1.8.1.2                       0    conda-forge
mayavi                    4.6.2            py36h18b3941_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.2           py36h8b7e671_1    conda-forge
openblas                  0.3.5                ha44fe06_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pcre                      8.43                 he6710b0_0  
pip                       19.0.3                   py36_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyface                    6.0.0                      py_1    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
python                    3.6.7             h381d211_1004    conda-forge
qt                        5.6.3                h8bf5577_3  
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tbb                       2019.5               hc9558a2_0    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traits                    5.0.0            py36h14c3975_0    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
vtk                       8.1.2           py36h8cc7ba1_1200    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Comment by grlee77** [comment]
Thanks. That looks like an ~6 month old build of `mayavi` combined with a more recent VTK 8.1.2. Good to see that 8.1.2 still seems okay (I think a user only reported regarding 8.1.1 in the prior issue).

As of some minutes ago, there is a newer build of mayavi, but I expect it should work the same for you as what you already have installed (the version of `mayavi` is the same, it was just rebuilt using a newer version of conda-forge's build scripts).
